apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vwyh4k9cu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vwyh4k9cu-go 
  name: vwyh4k9cu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vwyh4k9cu-go 
